server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/constella?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: constella
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

  spring:
    web:
      resources:
        static-locations: file:uploads/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
