  <application.yml>
  server:
    port: 8080


  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul&useSSL=false
      username: sa
      password:
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect : org.hibernate.dialect.MySQL8Dialect

          # show_sql: true
          format_sql: true
  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
  # org.hibernate.type: trace #??? ?? 2.x, hibernate5
  # org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6